# Site
title: lyyyuna 的小花园
subtitle: 动静中之动
description: lyyyuna 的小花园
author: lyyyuna
email: lyyyuna@outlook.com

url: https://www.lyyyuna.com
root: /

# Directory
source_dir: source
post_dir: posts
about_dir: about

output_dir: output
series_dir: series

index_now: fb77cde40e164bd691802d167948c46f

# analytics
analytics:
  >
  <div id="stats" class="icp"></div>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-1G7RNXMWQX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-1G7RNXMWQX');
  </script>
  <script async src="https://analytics.lyyyuna.com/v1/stats.js"></script>

deploy:
- type: git
  repository: git@github.com:lyyyuna/lyyyuna.github.io.git
  branch: master
