title = "lyyyuna 的小花园"
subtitle =  "动静中之动"
description = "lyyyuna 的小花园"
author = "lyyyuna"
language = "zh-CN"

# URL
url = "http://www.lyyyuna.com"
root = "/"

# Directory
source_dir = "source"
post_dir = "post"
template_dir = "template"

archive_dir = "archives"
category_dir = "category"

# Date / Time format
per_page = 10
pagination_dir = "page"

[menu]
Home = "/"
Archives = "/archives"
About = "/about"
Categories = "/categories"

[[deploy]]
repository = "git@github.com:lyyyuna/lyyyuna.github.io.git"
branch = "master"